language: generic
install: true
jobs:
  include:
    - stage: one
      script: echo hi
    - script: echo hallo
    - stage: two
      script: echo hola
    - script: echo ciao
    - script: echo aló
    - stage: three
      script: echo bye
    - script: echo agur
    - script: echo yogur
