language: ruby
cache: bundler

install: skip

os:
  - linux
  - osx
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.3

jobs:
  include:
    - os: osx
      osx_image: xcode7.3
    - stage: deploy
      script: echo "I'd deploy here..."
matrix:
  exclude:
    - os: osx
      rvm: 2.1.0
