conditions: v1

language: generic

install: skip

jobs:
  include:
    # Test libraries
    - &lib-test-stage
      stage: test libraries
      script:
        - COMPONENT_TYPE=lib ./ci/test.sh
      if: branch = env(BR)
      env: BR=esta A=1

    - <<: *lib-test-stage
      env: BR=esta B=1
