conditions: v1

language: go
go: 1.10.x

install: skip

jobs:
  include:

    # Test libraries
    - &lib-test-stage
      stage: test libraries
      script:
        - COMPONENT_TYPE=lib ./ci/test.sh
      if: branch = env(BR)
      env: BR=lib-library2-test-conditions A=1

    - <<: *lib-test-stage
      env: BR=lib-library2-test-conditions B=1
