language: ruby
cache: bundler

install: skip

os:
  - linux
  - osx
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.5
  - jruby

matrix:
  exclude:
    - rvm: 1.9.2
      os: osx
    - rvm: 2.1.0
      os: osx
    - rvm: jruby
      os: osx
jobs:
  include:
    - os: osx
      osx_image: xcode7.3
      rvm: 2.1.0
    - stage: deploy
      if branch = master
      script: echo "I'd deploy here..."
