conditions: v1

language: generic

install: skip

jobs:
  include:
    # Test libraries
    - &lib-test-stage
      stage: test libraries
      if: branch = env(BR)
      script:
        - echo hi
      env: BR=esta A=1

    - <<: *lib-test-stage
      env: BR=esta B=1
