conditions: v1

language: go
go: 1.10.x

install: skip

jobs:
  include:
    - &lib-test-stage
      stage: test libraries
      script: echo "this is a test"
      if: branch = main
      env: BR=lib-library2-test-conditions A=1
    - <<: *lib-test-stage
      env: BR=lib-library2-test-conditions B=1
